INSERT INTO paciente (prontuario, none, cpf,convenio,data_consulta,especialidade)
VALUES (11, 'Maria', 11111111111, 'unimed','2021-08-26','neurologia');
INSERT INTO paciente (prontuario, none, cpf,convenio,data_consulta,especialidade)
VALUES (25, 'Lucas', 22222222222, 'unimed','2021-09-11','cardiologia');
INSERT INTO paciente (prontuario, none, cpf,convenio,data_consulta,especialidade)
VALUES (7, 'ROSA', 33333333333, 'sus', '2021-09-08', 'psiquiatria');
INSERT INTO paciente (prontuario, none, cpf,convenio,data_consulta,especialidade)
VALUES (513,'Antonio', 44444444444, 'sus', '2021-08-29','ortopedia');